### ISSUE TITLE
Feature Request: Add support for merge queues

### ISSUE THREAD

**Issue by MichaelBlake-gingerio** [advanced-security/secret-scanning-review-action#39]
This action does not seem to support using merge queues. Here is the error we receive...
```
Action workflow must be run on 'pull_request'.  GITHUB_REF is not set to a pull request number
```

This is the yaml file we use for our workflow...

```
name: 'SAST Scans'
on:
  pull_request:
  merge_group:
jobs:
  secret-scanning-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Secret Scanning Review Action'
        uses: advanced-security/secret-scanning-review-action@v2.1.0
        with:
          token: ${{ secrets.SECRET_SCAN_REVIEW_GITHUB_TOKEN }}
          fail-on-alert: true
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          fail-on-severity: high
```

This is working great for all of our other repos that do not use a merge queue. Please let me know if this is out of scope of this project or if there's anything we're doing wrong that could fix this.

Thanks!
