### ISSUE TITLE
How to enable custom pattern

### ISSUE THREAD

**Issue by carmal891** [advanced-security/secret-scanning-review-action#7]
The official Github secret scanning documentation mentions defining custom patterns for secret scanning :
`https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/defining-custom-patterns-for-secret-scanning
`
Can we enable the same feature using the secret-scanning-review-action ?

**Comment by felickz** [comment]
My sample from the ReadMe is actually using a custom pattern `RSA Private Key` :) 

![Image](https://github.com/advanced-security/secret-scanning-review-action/assets/1760475/cb55d8ac-628d-44b9-b1c8-ff6452323135)

Once you dry one the pattern, publish the pattern and it will be available here!  To be 💯 clear, it would further be best to further enable the pattern for push protection so it should only show up in the case where it was bypassed!

**Comment by carmal891** [comment]
Thank you for the prompt response. However my question was whether it is possible to keep the pattern as code rather than utulize the repo UI console. For example like a .patterns file and then pass it to the action attributes


 ```
 Secret-Scanning-Job:
      needs: initial-setup-job
      runs-on: ubuntu-latest
      steps:     
      - name: Secret Scanning Review Action
        uses: advanced-security/secret-scanning-review-action@v0
        with:
          token: ${{ secrets.SECRET_SCAN_REVIEW_GITHUB_TOKEN }}
          fail-on-alert: true
          fail-on-alert-exclude-closed: false
          patterns-path: .patterns
```

Is something like this feasible ?
